#!/bin/bash

_kill_procs() {
  kill -TERM $chromium
  wait $chromium
  # kill -TERM $xvfb
}

# Setup a trap to catch SIGTERM and relay it to child processes
trap _kill_procs SIGTERM

XVFB_WHD=${XVFB_WHD:-1280x720x16}

# Start Xvfb
# note - this will fail if xvfb already exists, but that's fine,
# we don't have set -ex
# we can keep xvfb in background, kill when pod is killed

Xvfb :99 -ac -screen 0 $XVFB_WHD -nolisten tcp &
xvfb=$!
sleep 5

export DISPLAY=:99

chromium --no-sandbox $@ &
chromium=$!

wait $chromium
#kill -TERM $xvfb
#wait $xvfb
